### ISSUE TITLE
Research integrating logins with existing RAC authentication

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/aquila#12]
RAC staff will need to log in to the application in order to view, create, edit, and delete rights statements and groupings.

Research what it would look like to integrate with existing authentication at the RAC.

**Comment by helrond** [comment]
We have two options here:
1. Integrate with Active Directory/LDAP using a custom Django Authentication [backend](https://github.com/django-auth-ldap/django-auth-ldap). We initially did this for Aurora, and it's not too hard.
2. Integrate with our Single Sign On provider (ADFS). We've never done this before, but there appears to be a well-documented [package which supports this approach](https://django-auth-adfs.readthedocs.io/en/latest/index.html).

In talking with Jose, he recommends option number two, because that would potentially allow access outside of the RAC network, if we wanted to go that direction in the future. I doubt very much we'll want to do make this app available on the web, but you never know (global pandemics!) and SSO also makes things easier for end users. 

My recommendation would be to pursue the SSO option, which we'd need to do in collaboration with IT, since there is a fair amount of configuration necessary on the ADFS side of things.

(As a reference, we use ADFS 3.0)
