### ISSUE TITLE
Rights serializer is not creating expected output for policy, donor basis

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/aquila#124]
The rights serializer is currently creating JSON with "policy" and "donor" as a rights basis, instead of a rights basis of "other" with "policy" or "donor" as the other basis type. This is because "policy" and "donor" are stored as their own rights basis in the rights shell model, so some additional transformational work needs to be done before the JSON is properly serialized.

The rights serializer (or some method elsewhere?) should handle "policy" and "donor" rights shells by serializing them to a rights basis of "other" with "policy" or "donor" as the other basis type.

**Comment by helrond** [comment]
Changes made to rights statements should be checked against the structure Fornax expects to receive, as well as what is produced in Aurora. Ultimately we'll need to align all of these representations, so that we can effectively validate in Ursa Major (currently using a very out of date version of rac_schemas).
