### ISSUE TITLE
Improve display of date fields

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aquila#91]
## Is your feature request related to a problem? Please describe.
The current display of date fields is potentially really confusing to a user. Are there ways we can improve the interaction pattern or display to make things easier on users? 

<img width="813" alt="Screen Shot 2021-02-25 at 12 01 29 PM" src="https://user-images.githubusercontent.com/607621/109188908-6aaa2280-7761-11eb-9194-0acf3b4f5086.png">

## Describe the solution you'd like
Potential solution:
- Instead of displaying all the date inputs, display a select for both start date and end date. 
- For start date, the options would be:
  - "This restriction starts on a specific date" - if selected, displays the start_date field
  - "This restriction starts after an embargo period" - if selected, displays the start_date_period
- For end date, the options would be:
  - "This restriction ends on a specific date" - if selected, displays the end_date field
  - "This restriction ends after an embargo period" - if selected, displays the end_date_period
  - "There is no end date for this restriction" - doesn't display any input but the end_date_open boolean would be checked

One advantage to an approach like this is that it would make validation a lot easier. 

Are there accessibility implications of this kind of pattern?

## Additional context
Noting this was also an issue identified (but not fully solved) in Aurora testing.

**Comment by HaSistrunk** [comment]
I like this conditional display idea a lot! Another option would to be to add the selects as you specify, but instead of hiding the date fields, disable them until a selection is made. I think this would still be confusing, though, so I prefer you solution. 

I wonder if for "There is no end date for this restriction", the display of the end_date_open boolean should be readonly so that a user can't uncheck it once that selection is made?

Accessibility-wise, I think this works fine as long as the new form fields appear below the select, and focus does not change when a selection is made. This is outlined in [WCAG SC 3.2.2](https://www.w3.org/WAI/WCAG21/Understanding/on-input.html), although I'm not 100% clear about if this is a [change in context](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#context-changedef), or a change in content. I would argue it's content.

**Comment by helrond** [comment]
There is now a proof of concept in #93
